/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Chilaquiles;
import modelo.Conexion;
import modelo.Platillo;

/**
 *
 * @author caste
 */
public class Ventana_NuevaOrden extends javax.swing.JFrame {

    public ArrayList<Platillo> ordenes;
    //public ArrayList<Platillo> mesa1 = new ArrayList<Platillo>();
    public int mesa;
    public int numOrden = 0;
    
    public void crearModeloTabla(){
        tablaOrden.setModel(new DefaultTableModel(
            new Object[][] {
			},
		new String[] {
                    "Orden", "Nombre", "Tipo", "Precio"
                }
        )   {
		Class[] columnTypes = new Class[] {
                    String.class, String.class, Integer.class, Double.class
		};
                public Class getColumnClass(int columnIndex) {
                    return columnTypes[columnIndex];
		}
        }
        );
    }
    
    public void insertarOrdenChilaquiles(Chilaquiles chilaquiles){
        int idOrdenFinal=1;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        //System.out.println(dtf.format(now));
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaOrden.setModel(modeloTabla);
        
        PreparedStatement ps = null;
        ResultSet rs = null;
            try {
                Conexion con = new Conexion();
                Connection conexion = con.getConnection();
                
                //Codigo para obtener el ultimo IDORDEN (Para poder insertar en la tabla)
                ps = conexion.prepareStatement("SELECT idOrden, nombre, carne, precio FROM Orden");
                rs = ps.executeQuery();
                
                modeloTabla.addColumn("Orden");
		modeloTabla.addColumn("Nombre");
		modeloTabla.addColumn("Tipo"); 
		modeloTabla.addColumn("Precio"); 
                
                //Obtener toda la data de MySQL
                ResultSetMetaData rsMD = (ResultSetMetaData)rs.getMetaData();
                int cantidadColumnas = rsMD.getColumnCount();
                
                int anchos[] = {50, 100, 100,70};
                
                for(int i=0; i<cantidadColumnas; i++) {
                    tablaOrden.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
		}
                
                while(rs.next()){
                    idOrdenFinal = idOrdenFinal+1;//Codigo para obtener el ultimo IDORDEN (Para poder insertar en la tabla)
                    
                    //Agregando cada columna de la base de datos a objeto Fila
                    Object fila[] = new Object[cantidadColumnas];
                    for(int i=0; i<cantidadColumnas; i++) {
                        fila[i] = rs.getObject(i+1);
                    }
                    modeloTabla.addRow(fila);
                }
                
                //Codigo para insertar valores de menu chilaquiles
                ps = conexion.prepareStatement("INSERT INTO Orden (idOrden, numOrden, numMesa, precio, nombre, carne, salsa, estatus, fecha) "
                        + "values(?,?,?,?,?,?,?,?,?)");
                
                ps.setInt(1, idOrdenFinal);
                ps.setInt(2, numOrden);
                ps.setInt(3, mesa);
                ps.setDouble(4, chilaquiles.getPrecio());
                ps.setString(5, chilaquiles.getNombre());
                ps.setString(6, chilaquiles.getProteina());
                ps.setString(7, chilaquiles.getSalsa());
                ps.setString(8, "Activo");
                ps.setString(9, dtf.format(now));
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro insertado correctamente");
                    
            } catch (Exception e) {
                System.err.println(e);
            }
            
        System.out.println("ID =" + idOrdenFinal);
    }

    /**
     * Creates new form Ventana_NuevaOrden
     */
    public Ventana_NuevaOrden() {
        initComponents();
        setLocationRelativeTo(null);

        crearModeloTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MesaDialog = new javax.swing.JDialog();
        etiquetaNumMesa = new javax.swing.JLabel();
        etiquetaNumMesa1 = new javax.swing.JLabel();
        cajaNumMesa = new javax.swing.JTextField();
        cajaCantPersonas = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        Chilaquiles = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rBotonSencillos = new javax.swing.JRadioButton();
        rBotonRes = new javax.swing.JRadioButton();
        rBotonPuerco = new javax.swing.JRadioButton();
        rBotonPollo = new javax.swing.JRadioButton();
        rBotonAdobada = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rBotonSalsaVerde = new javax.swing.JRadioButton();
        rBotonSalsaRoja = new javax.swing.JRadioButton();
        botonAceptarCh = new javax.swing.JButton();
        grupoBotonProteinaCh = new javax.swing.ButtonGroup();
        grupoBotonSalsasCh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botonNuevaMesa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrden = new javax.swing.JTable();
        botonChilaquiles = new javax.swing.JButton();
        botonAlambres = new javax.swing.JButton();
        botonHamburguesas = new javax.swing.JButton();
        botonEnsaladas = new javax.swing.JButton();
        botonTacos = new javax.swing.JButton();
        botonQuesadillas = new javax.swing.JButton();
        botonCarnesAsadas = new javax.swing.JButton();
        botonAguaHorchata = new javax.swing.JButton();
        botonAguaLimon = new javax.swing.JButton();
        botonRefresco = new javax.swing.JButton();
        botonAguaMineral = new javax.swing.JButton();
        botonCerveza = new javax.swing.JButton();
        botonCubetaCerveza = new javax.swing.JButton();
        botonVasoChelado = new javax.swing.JButton();
        botonVasoMichelado = new javax.swing.JButton();
        botonVasoGringa = new javax.swing.JButton();
        botonCafeAmericano = new javax.swing.JButton();
        botonTe = new javax.swing.JButton();
        botonTisana = new javax.swing.JButton();
        botonAguaNatural = new javax.swing.JButton();

        MesaDialog.setLocation(new java.awt.Point(500, 200));
        MesaDialog.setMinimumSize(new java.awt.Dimension(300, 300));

        etiquetaNumMesa.setText("Numero de Mesa");

        etiquetaNumMesa1.setText("Cantidad de Personas");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MesaDialogLayout = new javax.swing.GroupLayout(MesaDialog.getContentPane());
        MesaDialog.getContentPane().setLayout(MesaDialogLayout);
        MesaDialogLayout.setHorizontalGroup(
            MesaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MesaDialogLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(MesaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar)
                    .addComponent(cajaCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNumMesa1)
                    .addGroup(MesaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cajaNumMesa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etiquetaNumMesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        MesaDialogLayout.setVerticalGroup(
            MesaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MesaDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(etiquetaNumMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaNumMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(etiquetaNumMesa1)
                .addGap(18, 18, 18)
                .addComponent(cajaCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botonAceptar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Chilaquiles.setMinimumSize(new java.awt.Dimension(460, 466));

        jLabel1.setText("TIPO DE PROTEINA");

        jLabel2.setText("CHILAQUILES");

        grupoBotonProteinaCh.add(rBotonSencillos);
        rBotonSencillos.setText("SENCILLOS");

        grupoBotonProteinaCh.add(rBotonRes);
        rBotonRes.setText("RES");

        grupoBotonProteinaCh.add(rBotonPuerco);
        rBotonPuerco.setText("PUERCO");

        grupoBotonProteinaCh.add(rBotonPollo);
        rBotonPollo.setText("POLLO");

        grupoBotonProteinaCh.add(rBotonAdobada);
        rBotonAdobada.setText("ADOBADA");

        jLabel3.setText("SALSAS");

        grupoBotonSalsasCh.add(rBotonSalsaVerde);
        rBotonSalsaVerde.setText("VERDE");

        grupoBotonSalsasCh.add(rBotonSalsaRoja);
        rBotonSalsaRoja.setText("ROJA");

        botonAceptarCh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/palomita_100x100.png"))); // NOI18N
        botonAceptarCh.setBorder(null);
        botonAceptarCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarChActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChilaquilesLayout = new javax.swing.GroupLayout(Chilaquiles.getContentPane());
        Chilaquiles.getContentPane().setLayout(ChilaquilesLayout);
        ChilaquilesLayout.setHorizontalGroup(
            ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChilaquilesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBotonSalsaRoja)
                    .addComponent(rBotonAdobada)
                    .addComponent(rBotonPollo)
                    .addComponent(rBotonPuerco)
                    .addComponent(rBotonRes)
                    .addComponent(rBotonSencillos)
                    .addComponent(rBotonSalsaVerde))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChilaquilesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChilaquilesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChilaquilesLayout.createSequentialGroup()
                        .addComponent(botonAceptarCh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        ChilaquilesLayout.setVerticalGroup(
            ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChilaquilesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rBotonSencillos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBotonRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBotonPuerco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBotonPollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBotonAdobada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(ChilaquilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rBotonSalsaVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBotonSalsaRoja)
                .addGap(18, 18, 18)
                .addComponent(botonAceptarCh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        botonNuevaMesa.setText("Nueva Mesa");
        botonNuevaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaMesaActionPerformed(evt);
            }
        });

        tablaOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaOrden);

        botonChilaquiles.setText("Chilaquiles");
        botonChilaquiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonChilaquilesActionPerformed(evt);
            }
        });

        botonAlambres.setText("Alambres");

        botonHamburguesas.setText("Hamburguesas");

        botonEnsaladas.setText("Ensaladas");

        botonTacos.setText("Tacos");

        botonQuesadillas.setText("Quesadillas");

        botonCarnesAsadas.setText("Carnes Asadas");

        botonAguaHorchata.setText("Agua Horchata");
        botonAguaHorchata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAguaHorchataActionPerformed(evt);
            }
        });

        botonAguaLimon.setText("Agua Limon");

        botonRefresco.setText("Refresco");

        botonAguaMineral.setText("Agua Mineral");

        botonCerveza.setText("Cerveza");

        botonCubetaCerveza.setText("Cubeta Cerveza");

        botonVasoChelado.setText("Vaso Chelado");

        botonVasoMichelado.setText("Vaso Michelado");

        botonVasoGringa.setText("Vaso Gringa");

        botonCafeAmericano.setText("Cafe Americano");

        botonTe.setText("Té");

        botonTisana.setText("Tisana");

        botonAguaNatural.setText("Agua Natural");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonEnsaladas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonChilaquiles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAlambres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonHamburguesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCarnesAsadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonQuesadillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTacos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCubetaCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(botonCerveza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAguaNatural, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAguaLimon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAguaHorchata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRefresco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAguaMineral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonCafeAmericano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTisana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVasoChelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVasoMichelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVasoGringa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(botonNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonChilaquiles, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAguaHorchata, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVasoChelado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAlambres, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonQuesadillas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAguaLimon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVasoMichelado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarnesAsadas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVasoGringa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEnsaladas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAguaMineral, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCafeAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAguaNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTisana, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCubetaCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaMesaActionPerformed
        MesaDialog.setVisible(true);
        numOrden++;
    }//GEN-LAST:event_botonNuevaMesaActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        mesa = Integer.parseInt(cajaNumMesa.getText());
        MesaDialog.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonChilaquilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonChilaquilesActionPerformed
        Chilaquiles.setVisible(true);
    }//GEN-LAST:event_botonChilaquilesActionPerformed

    private void botonAguaHorchataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAguaHorchataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAguaHorchataActionPerformed

    private void botonAceptarChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarChActionPerformed
        String nombre = "chilaquiles";
        String proteina = null;
        String salsa = null;
        double precio = 0;
        if(rBotonSencillos.isSelected()){
            proteina = "sencillos";
            precio = 60;
        }
        if(rBotonSalsaVerde.isSelected()){
            salsa = "salsa verde";
        }
        Chilaquiles chilaquiles = new Chilaquiles(proteina, salsa, nombre, precio, mesa);
        insertarOrdenChilaquiles(chilaquiles);
        
        Chilaquiles.dispose();
    }//GEN-LAST:event_botonAceptarChActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_NuevaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_NuevaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_NuevaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_NuevaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_NuevaOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Chilaquiles;
    private javax.swing.JDialog MesaDialog;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAceptarCh;
    private javax.swing.JButton botonAguaHorchata;
    private javax.swing.JButton botonAguaLimon;
    private javax.swing.JButton botonAguaMineral;
    private javax.swing.JButton botonAguaNatural;
    private javax.swing.JButton botonAlambres;
    private javax.swing.JButton botonCafeAmericano;
    private javax.swing.JButton botonCarnesAsadas;
    private javax.swing.JButton botonCerveza;
    private javax.swing.JButton botonChilaquiles;
    private javax.swing.JButton botonCubetaCerveza;
    private javax.swing.JButton botonEnsaladas;
    private javax.swing.JButton botonHamburguesas;
    private javax.swing.JButton botonNuevaMesa;
    private javax.swing.JButton botonQuesadillas;
    private javax.swing.JButton botonRefresco;
    private javax.swing.JButton botonTacos;
    private javax.swing.JButton botonTe;
    private javax.swing.JButton botonTisana;
    private javax.swing.JButton botonVasoChelado;
    private javax.swing.JButton botonVasoGringa;
    private javax.swing.JButton botonVasoMichelado;
    private javax.swing.JTextField cajaCantPersonas;
    private javax.swing.JTextField cajaNumMesa;
    private javax.swing.JLabel etiquetaNumMesa;
    private javax.swing.JLabel etiquetaNumMesa1;
    private javax.swing.ButtonGroup grupoBotonProteinaCh;
    private javax.swing.ButtonGroup grupoBotonSalsasCh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rBotonAdobada;
    private javax.swing.JRadioButton rBotonPollo;
    private javax.swing.JRadioButton rBotonPuerco;
    private javax.swing.JRadioButton rBotonRes;
    private javax.swing.JRadioButton rBotonSalsaRoja;
    private javax.swing.JRadioButton rBotonSalsaVerde;
    private javax.swing.JRadioButton rBotonSencillos;
    private javax.swing.JTable tablaOrden;
    // End of variables declaration//GEN-END:variables
}
